apiVersion: batch/v1
kind: Job
metadata:
    name: dk.job.ggr.scanmotifs.basset.lite
spec:
    template:
      spec:
        containers:
        - name: train-container
          image: dskim89/tensorflow-genomics
          env:
          - name: MODEL_DIR
            value: "/datasets/models.2018-12-03"
          - name: MODEL
            value: "basset"
          - name: OUT_DIR
            value: "/datasets/inference.2019-06-10/motifs.input_x_grad.lite"
          - name: FILTER
            value: "ATAC_LABELS=0,1,2,3,4,5,6,9,10,12::reduce_type=min,min=2"
          command: ["bash", "-c"]
          args: ["source ~/.bash_profile && mkdir -p $OUT_DIR && /datasets/software/git/tronn/scripts/ggr/kube/scanmotifs.lite.ggr.bash $MODEL_DIR $MODEL \"$FILTER\" $OUT_DIR"]
          resources:
            limits:
              nvidia.com/gpu: 6
              cpu: 8
              memory: 32Gi
            requests:
              cpu: 4
              memory: 20Gi
          volumeMounts:
          - mountPath: /datasets
            name: datasets
        restartPolicy: Never
        volumes:
        - name: datasets
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
             fsName: nautilusfs
             clusterNamespace: rook
             path: /kundajelab
             mountUser: kundajelab
             mountSecret: ceph-fs-secret
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: gpu-type
                  operator: In # Use NotIn for other types
                  values:
                  - "1080Ti"