apiVersion: v1
kind: Pod
metadata:
    name: dk.dev
spec:
    containers:
    - name: vol-container
      image: dskim89/tronn
      args: ["sleep", "infinity"]
      resources:
        limits:
          cpu: 2
          memory: 8Gi
        requests:
          cpu: 2
          memory: 8Gi
      volumeMounts:
      - mountPath: /datasets
        name: datasets
    restartPolicy: Never
    volumes:
    - name: datasets
      flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          fsName: nautilusfs
          clusterNamespace: rook
          path: /kundajelab
          mountUser: kundajelab
          mountSecret: ceph-fs-secret