# Config file for automatic testing at travis-ci.org
language: python

python:
  - 2.7

notifications:
  email: false

# Setup Anaconda
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  # Install in batch mode
  - ./miniconda.sh -b  -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH

install:
  - conda create --yes --name tronn_env python=$TRAVIS_PYTHON_VERSION
  - source activate tronn_env
  